server:
  port: 8888

spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/guzelberkay/Java14ConfigServer.git"
          default-label: "main"
          skip-ssl-validation: true
          username: "guzelberkay"
          password: ${JAVA14GITTOKEN}