server:
  port: 80

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: auth-service
            uri: http://localhost:9090 #hedef adres
            predicates:
              - Path=/auth/**
            filters:
              - name: RewritePath
                args:
                  regexp: "/(?<segment>.*)"
                  replacement: "/api/v1/${segment}"
              - name: CircuitBreaker
                args:
                  name: authCircuitBreaker
                  fallbackUri: forward:/fallback/auth