server:
  port: 9091


spring:
  zipkin:
    base-url: http://localhost:9411/
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
  data:
    mongodb:
      host: localhost
      port: 27027
      database: UserProfileDB
      username: bilge
      password: bilge!123

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      enabled: true

userservice:
  redis:
    host: localhost
    port: 6379